### ISSUE TITLE
IPv6 integration and configuration example IPv6

### ISSUE THREAD

**Issue by joehun** [f18m/ha-addon-dnsmasq-dhcp-server#13]
Hello,

is it possible also to assign IPv6 addresses? Can you please give an configuration example?

Best regards,
joehun

**Comment by f18m** [comment]
hey @joehun ,
Yes, IPv6 are supported. I'm not using them personally, but the implementation should be working just fine for both ipv4 and ipv6.
Config example:

```
ip_address_reservations:
- name: my-fancy-device
  mac: 40:ae:cc:50:ff:ff
  ip: 2001:db8:3333:4444:5555:6666:7777:8888
```

Let me know if you find any issue...
